server:
  port: 5150

spring:
  application:
    name: config-client
  config:
    import: configserver:http://localhost:8891

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/

