server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        # git:
        #  uri: https://github.com/dedosmedia/spring-cloud-config-server-configuration
        native:    #opcional si queremos trabajar la configuración local durante desarrollo
          search-locations: classpath:/config