server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        # git:
        #  uri: https://github.com/dedosmedia/configuraciones.git
        native:    #  Lo entrego en local, para evitar problemas...   sería quitar el perfil native y descomentar lo de arriba, eliminando lo de abajo
          searchLocations: classpath:/config